"""
Writes branding/banner.svg - the 2:1 banner used as README header and GitHub
social preview. Edit this and re-run; then run render_assets.py for the PNGs.

    "00 PYTHON\python.exe" branding\make_banner.py
"""
import math
import random
from pathlib import Path

W, H = 1280, 640
FONT = "Segoe UI, Inter, system-ui, sans-serif"
HERE = Path(__file__).resolve().parent


def mark(scale, tx, ty):
    s = []
    s.append(f'  <g transform="translate({tx} {ty}) scale({scale})">')
    s.append('    <rect x="8" y="8" width="240" height="240" rx="52" fill="url(#tile)"/>')
    s.append('    <rect x="8.5" y="8.5" width="239" height="239" rx="52" fill="none" stroke="#2a313c" stroke-width="1"/>')
    s.append('    <path d="M 52 196 C 70 150, 96 156, 116 132" fill="none" stroke="#38bdf8" stroke-width="4" stroke-linecap="round" opacity="0.45"/>')
    s.append('    <circle cx="52" cy="196" r="7" fill="#38bdf8" opacity="0.45"/>')
    s.append('    <circle cx="72" cy="160" r="8" fill="#38bdf8" opacity="0.65"/>')
    s.append('    <circle cx="96" cy="152" r="9" fill="#38bdf8" opacity="0.85"/>')
    s.append('    <circle cx="140" cy="108" r="54" fill="none" stroke="#38bdf8" stroke-width="12"/>')
    for x1, y1, x2, y2 in ((140, 22, 140, 52), (140, 164, 140, 194), (54, 108, 84, 108), (196, 108, 226, 108)):
        s.append(f'    <line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="#38bdf8" stroke-width="12" stroke-linecap="round"/>')
    s.append('    <circle cx="140" cy="108" r="13" fill="#ffffff"/>')
    s.append('    <circle cx="140" cy="108" r="6" fill="#3ddc84"/>')
    s.append('  </g>')
    return s


def main():
    out = []
    a = out.append
    a(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" height="{H}">')
    a('  <!-- Automated Tracker banner. Generated by branding/make_banner.py - edit that, not this file. -->')
    a('  <defs>')
    a('    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">')
    a('      <stop offset="0" stop-color="#14171d"/><stop offset="1" stop-color="#0a0c10"/>')
    a('    </linearGradient>')
    a('    <radialGradient id="glow" cx="0.82" cy="0.18" r="0.55">')
    a('      <stop offset="0" stop-color="#38bdf8" stop-opacity="0.22"/>')
    a('      <stop offset="1" stop-color="#38bdf8" stop-opacity="0"/>')
    a('    </radialGradient>')
    a('    <linearGradient id="tile" x1="0" y1="0" x2="1" y2="1">')
    a('      <stop offset="0" stop-color="#1a1e25"/><stop offset="1" stop-color="#0d0f13"/>')
    a('    </linearGradient>')
    a('  </defs>')
    a(f'  <rect width="{W}" height="{H}" fill="url(#bg)"/>')
    a(f'  <rect width="{W}" height="{H}" fill="url(#glow)"/>')

    # dot grid - the feature points a tracker sees
    a('  <g fill="#98a1b0" opacity="0.16">')
    for y in range(40, H, 40):
        for x in range(40, W, 40):
            a(f'    <circle cx="{x}" cy="{y}" r="1.4"/>')
    a('  </g>')

    # tracked trails, kept in the top-right band so they never cross the text
    rnd = random.Random(11)
    trails = []
    for _ in range(5):
        x0 = rnd.randint(720, 1080)
        y0 = rnd.randint(70, 150)
        ang = rnd.uniform(-0.45, 0.35)
        pts = [(x0, y0)]
        for _k in range(5):
            ang += rnd.uniform(-0.3, 0.3)
            L = rnd.randint(28, 44)
            x0 += L * math.cos(ang)
            y0 = min(max(y0 + L * math.sin(ang), 40), 190)
            pts.append((x0, y0))
        trails.append(pts)
    a('  <g fill="none" stroke="#38bdf8" stroke-width="2" stroke-linecap="round" opacity="0.5">')
    for pts in trails:
        a('    <path d="M ' + ' L '.join(f'{x:.1f} {y:.1f}' for x, y in pts) + '"/>')
    a('  </g>')
    for pts in trails:
        n = len(pts) - 1
        for j, (x, y) in enumerate(pts):
            a(f'  <circle cx="{x:.1f}" cy="{y:.1f}" r="{2.2 + 1.6 * j / n:.1f}" fill="#38bdf8" opacity="{0.25 + 0.75 * j / n:.2f}"/>')
        x, y = pts[-1]
        a(f'  <circle cx="{x:.1f}" cy="{y:.1f}" r="7" fill="none" stroke="#3ddc84" stroke-width="2" opacity="0.9"/>')

    out += mark(0.95, 96, 168)

    a(f'  <text x="372" y="292" font-family="{FONT}" font-size="86" font-weight="700" fill="#e3e7ee">Automated Tracker</text>')
    a('  <rect x="376" y="312" width="120" height="4" rx="2" fill="#38bdf8"/>')
    a(f'  <text x="376" y="362" font-family="{FONT}" font-size="30" fill="#98a1b0">2D point tracking and 3D camera solves for VFX,</text>')
    a(f'  <text x="376" y="402" font-family="{FONT}" font-size="30" fill="#98a1b0">on your own machine.</text>')

    x = 376
    for c in ("CoTracker3", "COLMAP", "Nuke", "After Effects", "Blender", "USD"):
        w = 22 + int(len(c) * 11.2)
        a(f'  <rect x="{x}" y="446" width="{w}" height="38" rx="19" fill="#132735" stroke="#1e7fb0" stroke-width="1"/>')
        a(f'  <text x="{x + w / 2:.0f}" y="472" text-anchor="middle" font-family="{FONT}" font-size="18" font-weight="600" fill="#38bdf8">{c}</text>')
        x += w + 12
    a('</svg>')
    (HERE / "banner.svg").write_text("\n".join(out) + "\n", encoding="utf-8")
    print("banner.svg written")


if __name__ == "__main__":
    main()
